# Programming Assignment

# Question 1

# Use dictionaries to create below Information. 
## Step:
- Group the books by their author
- Use functions that takes dictionary as an input from user and return below information.
- Please note: You will pass a single nested dictionary to function. An example of nested dictionary is mentioned below showing only one book. However, you are going to pass 5 books to function. 

----------------------------------------------------------------------------------------
# Information
- Author: John Smith
  - Book Book1: Python for Beginners (2019)
  - Book Book3: The Art of Programming (2017)
- Author: Emily Johnson
  - Book Book2: Data Science Handbook (2020)
- Author: Andrew Brown
  - Book Book4: Machine Learning Basics (2023)
  - Book Book5: Deep Learning (2023)

In [11]:
books = {
    "Book1": {"title": "Python for Beginners", "author": "John Smith", "publication_year": 2019}
}

# Question 2 

In [ ]:
# Text to find words and their frequency
'''
Generating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. 
The writer has no idea what topic the random paragraph will be about when it appears. 
This forces the writer to use creativity to complete one of three common writing challenges. 
The writer can use the paragraph as the first one of a short story and build upon it. 
A second option is to use the random paragraph somewhere in a short story they create. 
The third option is to have the random paragraph be the ending paragraph in a short story. 
No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing
'''

# Genereate output like below

## Steps:
- Below is a list, and inside it we have tuples, which are showing unique words and their frequency in the paragraph, you can see text (Paragraph above)
- Create a function that does all this Job
- Then using matplotlib python library to generate a graph which shows words in x-axis and their frequency on y-axis. Note: Show top 25 words after sorting them from highest frequency to lowest

In [ ]:
[('generating', 1), ('random', 4), ('paragraphs', 1), ('can', 2), ('be', 3)]

In [ ]:
# Note: Above are just five tuples. However, you will get more than that!

# Question 3

# NumPy & Lists / Let's have a look at few Functions, and why numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy

In [35]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [36]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [37]:
np.array(my_list)

array([1, 2, 3])

In [38]:
# Question: What is the main difference between list and array input?
# Please read stackoverflow post and write answer, with few examples, which we have discussed in the class!

In [20]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# Question how to extract value 5 and 9 from above matrix

## Random 

Numpy also has lots of ways to create random number arrays:

Do you remember! Random modules!. ?  Yes!

Question: Then ! Create an array of two random samples from a uniform distribution
over ``[0, 1)``.

In [25]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
# Use built-in numpyt function to find Minimimum, Maximum, Index of Minimum Value and Index of Maximum Value


In [27]:
#Minimum

In [28]:
#Maximum

In [29]:
# Minimum Value Index

In [34]:
# Maximum Value Index 

# List any three methods provided to you by numpy, which we solved manually in the class instead of using pre-defined functions, with examples

In [ ]:
#Done